INSERT INTO PUBLIC.OWNER (NAME, MAIL) VALUES ('franck', 'franck.mazzolo@gmail.com');
INSERT INTO PUBLIC.OWNER (NAME, MAIL) VALUES ('isabelle', 'isabelle.mazzolo@gmail.com');

INSERT INTO PUBLIC.VEHICLE (BRAND, MODEL, PURCHASE_DATE, CURRENT_MILEAGE, LAST_MILEAGE_UPDATE, PRICE, OWNER_ID) VALUES ('yamaha', 'mt09', '2024-05-09', 10600, '2024-05-07', null, 1);
INSERT INTO PUBLIC.VEHICLE (BRAND, MODEL, PURCHASE_DATE, CURRENT_MILEAGE, LAST_MILEAGE_UPDATE, PRICE, OWNER_ID) VALUES ('fiat', 'grande punto', '2024-05-18', 50000, '2024-05-03', null, 2);

INSERT INTO PUBLIC.ACCESSORY (NAME, PRICE, PURCHASE_DATE, VEHICLE_ID) VALUES ('test', null, null, 1);

INSERT INTO PUBLIC.OPERATION (TYPE, PERIODICITY_MILEAGE, PERIODICITY_MONTH, VEHICLE_ID) VALUES ('vidange', 10000, 12, 1);
INSERT INTO PUBLIC.OPERATION (TYPE, PERIODICITY_MILEAGE, PERIODICITY_MONTH, VEHICLE_ID) VALUES ('bougies', 40000, null, 1);

INSERT INTO PUBLIC.HISTORY (DATE, COMMENT, LINK, PRICE, MILEAGE, OPERATION_ID) VALUES ('2024-04-09', null, null, null, 10000, 1);
INSERT INTO PUBLIC.HISTORY (DATE, COMMENT, LINK, PRICE, MILEAGE, OPERATION_ID) VALUES ('2024-03-07', null, null, null, 4000, 2);